# Generated by Django 4.2 on 2026-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_studentprofile_profile_image_alter_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
