# Generated by Django 4.2 on 2026-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
