# Generated by Django 4.2 on 2026-04-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_assignment_notice_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
