# Generated by Django 4.2 on 2026-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_studentprofile_bio_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bonus_marks',
            field=models.IntegerField(default=0),
        ),
    ]
