# Generated by Django 4.2 on 2026-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_badge_quiz_start_time_activitylog_earnedbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(choices=[('quiz_count', 'Total Quizzes Completed'), ('high_score', 'Specific Quiz Full Score'), ('resource_download', 'Resources Downloaded'), ('total_score_threshold', 'Total Milestone Score'), ('leaderboard_rank', 'Leaderboard Rank'), ('no_penalty_full_score', 'Full Score with No Penalty'), ('consistency_streak', 'Consistent High Performer')], max_length=50),
        ),
    ]
