# Generated by Django 4.2 on 2026-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0015_readnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
