# Generated by Django 4.2 on 2026-04-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0017_notice_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='attachment',
        ),
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quiz_app.notice')),
            ],
        ),
    ]
