# Generated by Django 4.2 on 2026-04-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0019_alter_notice_options_notice_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
