# Generated by Django 4.2 on 2026-04-21 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0020_assignmentsubmission_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
