# Generated by Django 4.2 on 2026-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0022_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='view_timestamps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
