# Generated by Django 4.2 on 2026-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0023_studentprofile_view_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/submissions/'),
        ),
    ]
