# Generated by Django 4.2 on 2026-04-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0027_notice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(choices=[('quiz_count', 'Total Quizzes Completed'), ('high_score', 'Specific Quiz Full Score'), ('resource_download', 'Resources Downloaded'), ('total_score_threshold', 'Total Milestone Score'), ('leaderboard_rank', 'Leaderboard Rank'), ('no_penalty_full_score', 'Full Score with No Penalty'), ('consistency_streak', 'Consistent High Performer'), ('total_tab_switches', 'Total Tab Switches (Looser)'), ('attendance_streak', 'Consecutive Attendance Days'), ('early_bird_quiz', 'Quiz Submitted Within 1 Hour of Publish'), ('assignment_full_marks', 'Full Marks in Assignments')], max_length=50),
        ),
    ]
