# Generated by Django 4.2 on 2026-04-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0028_alter_badge_requirement_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earnedbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='earnedbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='earnedbadge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='EarnedBadge',
        ),
    ]
