# Generated by Django 4.2 on 2026-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0029_alter_earnedbadge_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assignment_bonus_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='attendance_bonus_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='quiz_bonus_marks',
            field=models.IntegerField(default=0),
        ),
    ]
